[package]
name = "flat-manager"
version = "0.3.4"
authors = ["Alexander Larsson <alexander.larsson@gmail.com>"]
license = "MIT OR Apache-2.0"
# Needs nightly, so disable for now:
# default-run = "repo-manager"

[lib]
name = "flatmanager"
path = "src/lib.rs"

[dependencies]
env_logger = "0.5"

actix = "0.7"
actix-net = "0.2"
actix-web = "0.7"
askama = "0.7"

futures = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4.6", features = ["serde"] }
diesel = { version = "^1.3.0", features = ["postgres", "chrono", "serde_json", "r2d2"] }
diesel_migrations = { version = "^1.3.0" }
r2d2 = "0.8"
dotenv = "0.10"
tempfile = "3.0"
failure = "0.1.2"
jsonwebtoken = "5"
base64 = "0.9"
log = "0.4"
libc = "0.2"
argparse = "0.2.2"
walkdir = "2"
byteorder = "1.3"
hex = "0.3"
filetime = "0.2"
num_cpus = "1.0"
time = "0.1"
tokio = "0.1"
tokio-process = "0.2"
mpart-async = "0.2"
futures-fs = "0.0"
rand = "0.6"
futures-locks = "0.3"
